### PR TITLE
Update README / deploy instructions

### PR DESCRIPTION
**Pull request by jessieay**
**Why**:
* Other instructions were confusing, maybe inaccurate?
* Could not deploy with manifest that didn't include Ruby buildpack. The
  default that is used does not have Ruby 2.3.3 yet

### CODE REVIEW

**Comment by pkarman** [comment]
The changes look sane.

IIRC there was a need for basic auth and that's why the deploy env was used in the manifest creation previously. I've not checked this myself on cloud.gov -- is basic auth working for you when you deploy?

**Comment by jessieay** [comment]
When I deployed to my sandbox, there was no basic auth required to view the site.

Login was not working, but I assume that's because my app's config isn't on the idp yet

**Comment by pkarman** [comment]
Looks like the basic auth code got yanked in 0d17a00ad00b44525b9b481114e8899425de1355 when we left cloud.gov and started running our own nginx config.

Until this app is ATO'd I think it needs basic auth. You might check out f4feaf97bad28a1b9b378c454dd43537fba24cc7 for details on how that was done before.

In any case, that's why the README was out of date and why that deploy script existed before. If you implement basic auth some other way, that's fine. It just needs to be there.

**Comment by jessieay** [comment]
@pkarman re-added basic auth at c012d8a

**Comment by pkarman** [comment]
lgtm @jessieay

**Pull request merged**
