### PR TITLE
Remove references to cloud.gov

### PR DESCRIPTION
**Pull request by pkarman**
**Why**: Deployment is on par with our other identity apps.

### CODE REVIEW

**Comment by amoose** [comment]
Do we actually want to remove this? I think we should retain this information.

**Comment by amoose** [comment]
We have login.gov-specific deployment instructions https://github.com/18F/identity-sp-rails#deploy-to-logingov-lower-envs

**Comment by pkarman** [comment]
I think it's misleading to mention cloud.gov when we do not deploy there. The history is in the repo but newcomers will be confused.

**Comment by jessieay** [comment]
I just deployed this to my cloud.gov sandbox to test it out. Was that not right? See  https://github.com/18F/identity-sp-rails/pull/48

**Comment by pkarman** [comment]
since https://github.com/18F/identity-sp-rails/pull/42#issuecomment-258236642 cloud.gov is back on the menu.

**Pull request closed without merging**
