### PR TITLE
UI tweaks / fixes

### PR DESCRIPTION
**Pull request by brendansudol**
**Why**: improve loa1/3 form toggle & success bar

### CODE REVIEW

**Comment by brendansudol** [comment]
updated rails (and related gems) to resolve some new security vulnerabilities with our older rails version

**Comment by monfresh** [comment]
Can you please update the gems in a separate PR, then merge it into this branch? Thanks!

**Comment by brendansudol** [comment]
addressed!

**Comment by jgrevich** [comment]
👍 :shipit:

**Pull request merged**
